### ISSUE TITLE
Colocar informações sobre Struct e Type

### ISSUE THREAD

**Issue by vmesel** [crgimenes/Go-Hands-On#13]
Como comentado no evento da Red Hat, poderia ser colocada informações sobre struct e type no hands-on!

**Comment by crgimenes** [comment]
Sim, vou escrever um exemplo, bem lembrado!

**Comment by vmesel** [comment]
@crgimenes acho que você acabou esta parte no tutorial, certo?

**Comment by crgimenes** [comment]
Acho que sim, talvez precise de um pouco de polimento mas já da para usar.
