### ISSUE TITLE
Exemplos usando play.golang.org direto na pagina

### ISSUE THREAD

**Issue by crgimenes** [crgimenes/Go-Hands-On#21]
Inicialmente eu não separei o material em diretórios porque o numero de arquivos era pequeno e eu queria uma interação mais fluida e direta nos meus workshops, mas graças as contribuições o numero de arquivos esta crescendo e alguns exemplos ficariam melhor em múltiplos arquivos.

A ideia é criar um diretório para cada exemplo assim como hoje temos os arquivos exemplo.md e exemplo.go teríamos o diretório exemplo/ e dentro deles os arquivos 

ficando:
exemplo/exemplo.md
exemplo/exemplo.go

**Comment by crgimenes** [comment]
Pensando melhor no lugar de exemplo.md é mais util usar README.md, dessa forma o github já renderiza o markdown quando o usuário entra no diretório.

**Comment by aalvesjr** [comment]
@crgimenes acha interessante adicionar ao final do README.md, de cada exemplo/exercício, um link com o conteúdo no `play.golang.org` ? Assim a pessoa ao passar o olho pelo tutorial poderia já clicar e testar online mesmo.

Algo assim:
https://play.golang.org/p/Dl98B8pDmm

**Comment by crgimenes** [comment]
Acho a ideia muito boa! 

Partindo desse principio, sei que tem um modo de colocar o play embutido em uma pagina, não encontrei como faz isso nem sei se da para fazer aqui no github (https provavelmente vai reclamar de cross site). Se encontrarmos seria muito legal também.

**Comment by aalvesjr** [comment]
Legal, vale a pesquisa realmente 👍

**Comment by aalvesjr** [comment]
encontrei isso, https://blog.golang.org/playground#TOC_7.

**Comment by rgerardi** [comment]
Oi pessoal, já estou separando o material existente em diretórios. Alguém está trabalhando nisso? Só para evitar conflitos.

**Comment by rgerardi** [comment]
Mandei um PR com os arquivos separados em diretórios e os links apontando para os lugares certo. Só não mudei os arquivos senoide.* porque não vi a referência na página. Dá uma olhada e me avise.

**Comment by crgimenes** [comment]
Opa, PR aprovado.
Quanto ao senoide eu ainda não sei one colocar no READEME por isso não esta referenciando ainda.

**Comment by crgimenes** [comment]
O certo seria criar outra issue mas como já estávamos discutindo aqui eu apenas renomeei e reabri a issue.

**Comment by crgimenes** [comment]
Encontrei esse material aqui na comunidade mexicana https://github.com/xiam/go-playground bem interessante!

**Comment by crgimenes** [comment]
Usar playground direto na pagina é possível mas da problema com cross scripting e torna a edição da pagina mais complicada porque teríamos que inserir trechos html no meio do markdown e temos usuários que usam apenas o modo texto (deficiente visual que usa leitor de tela)

**Comment by crgimenes** [comment]
coloquei um link para o Playground em todos os exemplos em que isso cabia.
