### ISSUE TITLE
Links no rodapé

### ISSUE THREAD

**Issue by crgimenes** [crgimenes/Go-Hands-On#26]
Os links no rodapé para levar de uma pagina para outra parecem interessantes em um primeiro momento mas complica um pouco na hora de adicionar material novo ou mudar a ordem dos tutoriais. 
A pergunta é vale a pena manter esses links?

**Comment by aalvesjr** [comment]
Eu curto o modelo atual de ter links para o anterior e o próximo assunto.

> Se for mantido como está, talvez uma menção a isso no `Como contribuir` seja suficiente para garantir que materiais novos mantenham o fluxo anterior.

**Comment by crgimenes** [comment]
Também acho legal para quem esta acompanhando... tutorial a tutorial.
Bom então acho que isso termina com a discussão, alguém tem algum argumento contra os links no rodapé alem de serem chatos de atualiza?

**Comment by crgimenes** [comment]
links corrigidos e instruções adicionadas no CONTRIBUTING.md
