### ISSUE TITLE
Interfaces

### ISSUE THREAD

**Issue by crgimenes** [crgimenes/Go-Hands-On#3]
No ultimo evento o pessoal pediu para explicar interfaces, coisa que eu tinha deixado de fora assim como structs para evitar complexidade em um material que teoricamente devi ser básico para instalar o ambiente e iniciar em go para quem nunca viu nada... mas parece que crescer é inevitável, então é necessário bolar uma forma simples e didática de explicar interfaces e structs.

**Comment by gpaixao** [comment]
Booooa, vou curtir dms :smiley:

**Comment by crgimenes** [comment]
@gpaixao você pode me fazer um favor, adiciona um exemplo .go para acompanhar o material que você escreveu. O motivo é que o conteúdo foi feito para ser usado em workshops e treinamentos e os alunos devem poder testar na hora o conteúdo digitando um simples go run exemplo.go
o nome do arquivo .go deve ter o mesmo nome do arquivo .md, caso tenha mais de um exemplo é só colocar 2.go, 3.go, e assim por diante.

Obrigado pela ajuda!

**Comment by gpaixao** [comment]
Fechou essa issue com o merge de #6

**Comment by crgimenes** [comment]
Já usei a nova pagina com as interfaces no ultimo evento e foi bem legal mas precisamos incluir mais exemplo e casos de uso. O conceito confunde um pouco ainda.
